test:
  adapter: postgresql
  host: localhost
  database: api_test
  username: postgres
  password: postgres

development:
  adapter: postgresql
  host: localhost
  database: api_development
  username: postgres
  password: postgres

production:
  adapter: postgresql
  host:     localhost
  database: api_production
  username: postgres
  password: postgres
